### ISSUE TITLE
PrintReceiverActivity

### ISSUE THREAD

**Issue by harikrishna1213** [dimagi/zebra-print-android#3]
PrintReceiverActivity is expecting getStringArrayListExtra("zebra:bundle_list"), but what to pass when launching this activity? It is given that only "zebra:template_file_path" and barcode_data and text_data are passed to that activity.  Hence, it is always throwing RunTimeException.

**Comment by ctsims** [comment]
Hi,

Sorry about that, the README was out of date.

The print receiver now permits printing multiple jobs with one request, so instead of passing the bundle details for the print job individually, you attach multiple bundles, each with one job. The bundle_list is a list of keys for the bundles.

I've updated the README to reflect this usage.

**Comment by harikrishna1213** [comment]
Thanks for the update. What are barcodeData and textData in the given example? Where do we get them from?

**Comment by ctsims** [comment]
Those are application specific. ZPL labels can contain Variables which are filled in when a print occurs, the example provided presumes that the ZPL file contains two variables (named `barcode_data` and `text_data` in the ZPL file), and this code is sending values to fill in for those two variables to the printer due to logic internal to the app.

It sounds like this is wrapped up with the README update, so I'm going to close out the issue.
